In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('raw_data.csv')
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

# apply fnx

In [3]:
# feature engineering 

df2 = df.copy()

df2['tax'] = df2['income'].apply(lambda x:'20%' if x>= 60000 else "10%")

df2

    id          name   age country   gender   income  tax
0    1      John Doe  29.0     USA     Male  55000.0  10%
1    1      John Doe  29.0     USA     Male  55000.0  10%
2    2    Jane Smith   NaN  Canada   Female  62000.0  20%
3    3          Alex   NaN     USA  Unknown  47000.0  10%
4    4  Maria Garcia  34.0   Spain   Female      NaN  10%
5    5        Li Wei  27.0   China     Male  51000.0  10%
6    6           NaN  45.0   India   Female  73000.0  20%
7    7    Ahmed Khan  38.0     NaN     Male  68000.0  20%
8    8    Rachel Lee  29.0     USA   Female  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0  10%
10  10   Emily Davis  31.0     USA      NaN  58000.0  10%

# Map fnx

In [4]:
# suppose we want to convert Male => M , Female => F , Unknown => U

gender_map = { 'Male' : "M" , "Female":'F',"Unknown":'U' }
df2['gender'] = df2['gender'].map(gender_map)
df2

    id          name   age country gender   income  tax
0    1      John Doe  29.0     USA      M  55000.0  10%
1    1      John Doe  29.0     USA      M  55000.0  10%
2    2    Jane Smith   NaN  Canada      F  62000.0  20%
3    3          Alex   NaN     USA      U  47000.0  10%
4    4  Maria Garcia  34.0   Spain      F      NaN  10%
5    5        Li Wei  27.0   China      M  51000.0  10%
6    6           NaN  45.0   India      F  73000.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%
8    8    Rachel Lee  29.0     USA      F  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%
10  10   Emily Davis  31.0     USA    NaN  58000.0  10%

# Assign fnx

In [5]:
df2=  df2.assign(new_income = df2['income'] * 1.1 )
df2

    id          name   age country gender   income  tax  new_income
0    1      John Doe  29.0     USA      M  55000.0  10%     60500.0
1    1      John Doe  29.0     USA      M  55000.0  10%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN     USA      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0     USA      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0     USA    NaN  58000.0  10%     63800.0

In [6]:
df2

    id          name   age country gender   income  tax  new_income
0    1      John Doe  29.0     USA      M  55000.0  10%     60500.0
1    1      John Doe  29.0     USA      M  55000.0  10%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN     USA      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0     USA      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0     USA    NaN  58000.0  10%     63800.0

# Replace Fnx

In [7]:
df2['country'] = df2['country'].replace('USA',"United State")
df2

    id          name   age       country gender   income  tax  new_income
0    1      John Doe  29.0  United State      M  55000.0  10%     60500.0
1    1      John Doe  29.0  United State      M  55000.0  10%     60500.0
2    2    Jane Smith   NaN        Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN  United State      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0         Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0         China      M  51000.0  10%     56100.0
6    6           NaN  45.0         India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0           NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0  United State      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN        Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0  United State    NaN  58000.0  10%     63800.0

In [8]:
# some more fnx

In [9]:
# change column names 

df2.columns = ['Id',"Name","Age","Country","Gender","Income","Tax","New_Income"]
df2

    Id          Name   Age       Country Gender   Income  Tax  New_Income
0    1      John Doe  29.0  United State      M  55000.0  10%     60500.0
1    1      John Doe  29.0  United State      M  55000.0  10%     60500.0
2    2    Jane Smith   NaN        Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN  United State      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0         Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0         China      M  51000.0  10%     56100.0
6    6           NaN  45.0         India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0           NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0  United State      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN        Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0  United State    NaN  58000.0  10%     63800.0

# Rename fnx

In [10]:
df2.rename(columns={'Income':'Salary'})

    Id          Name   Age       Country Gender   Salary  Tax  New_Income
0    1      John Doe  29.0  United State      M  55000.0  10%     60500.0
1    1      John Doe  29.0  United State      M  55000.0  10%     60500.0
2    2    Jane Smith   NaN        Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN  United State      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0         Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0         China      M  51000.0  10%     56100.0
6    6           NaN  45.0         India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0           NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0  United State      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN        Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0  United State    NaN  58000.0  10%     63800.0

In [11]:
df2

    Id          Name   Age       Country Gender   Income  Tax  New_Income
0    1      John Doe  29.0  United State      M  55000.0  10%     60500.0
1    1      John Doe  29.0  United State      M  55000.0  10%     60500.0
2    2    Jane Smith   NaN        Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN  United State      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0         Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0         China      M  51000.0  10%     56100.0
6    6           NaN  45.0         India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0           NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0  United State      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN        Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0  United State    NaN  58000.0  10%     63800.0

In [12]:
df2.rename(index = {1:'First'})

       Id          Name   Age       Country Gender   Income  Tax  New_Income
0       1      John Doe  29.0  United State      M  55000.0  10%     60500.0
First   1      John Doe  29.0  United State      M  55000.0  10%     60500.0
2       2    Jane Smith   NaN        Canada      F  62000.0  20%     68200.0
3       3          Alex   NaN  United State      U  47000.0  10%     51700.0
4       4  Maria Garcia  34.0         Spain      F      NaN  10%         NaN
5       5        Li Wei  27.0         China      M  51000.0  10%     56100.0
6       6           NaN  45.0         India      F  73000.0  20%     80300.0
7       7    Ahmed Khan  38.0           NaN      M  68000.0  20%     74800.0
8       8    Rachel Lee  29.0  United State      F  62000.0  20%     68200.0
9       9   Carlos Ruiz   NaN        Mexico      M  45000.0  10%     49500.0
10     10   Emily Davis  31.0  United State    NaN  58000.0  10%     63800.0

# Sort Values

In [13]:
# we want to sort the data on the basis of income 

df2['Age'] = df2['Age'].fillna(50)

df2.sort_values('Income')
df2.sort_values(['Income'],ascending = False)
sorted_df = df2.sort_values(['Income' , 'Age'])
sorted_df

    Id          Name   Age       Country Gender   Income  Tax  New_Income
9    9   Carlos Ruiz  50.0        Mexico      M  45000.0  10%     49500.0
3    3          Alex  50.0  United State      U  47000.0  10%     51700.0
5    5        Li Wei  27.0         China      M  51000.0  10%     56100.0
0    1      John Doe  29.0  United State      M  55000.0  10%     60500.0
1    1      John Doe  29.0  United State      M  55000.0  10%     60500.0
10  10   Emily Davis  31.0  United State    NaN  58000.0  10%     63800.0
8    8    Rachel Lee  29.0  United State      F  62000.0  20%     68200.0
2    2    Jane Smith  50.0        Canada      F  62000.0  20%     68200.0
7    7    Ahmed Khan  38.0           NaN      M  68000.0  20%     74800.0
6    6           NaN  45.0         India      F  73000.0  20%     80300.0
4    4  Maria Garcia  34.0         Spain      F      NaN  10%         NaN

# Reset index

In [18]:
sorted_df.reset_index()
sorted_df.reset_index(drop = True)

    Id          Name   Age       Country Gender   Income  Tax  New_Income
0    9   Carlos Ruiz  50.0        Mexico      M  45000.0  10%     49500.0
1    3          Alex  50.0  United State      U  47000.0  10%     51700.0
2    5        Li Wei  27.0         China      M  51000.0  10%     56100.0
3    1      John Doe  29.0  United State      M  55000.0  10%     60500.0
4    1      John Doe  29.0  United State      M  55000.0  10%     60500.0
5   10   Emily Davis  31.0  United State    NaN  58000.0  10%     63800.0
6    8    Rachel Lee  29.0  United State      F  62000.0  20%     68200.0
7    2    Jane Smith  50.0        Canada      F  62000.0  20%     68200.0
8    7    Ahmed Khan  38.0           NaN      M  68000.0  20%     74800.0
9    6           NaN  45.0         India      F  73000.0  20%     80300.0
10   4  Maria Garcia  34.0         Spain      F      NaN  10%         NaN

# sort index

In [19]:
sorted_df.sort_index()

    Id          Name   Age       Country Gender   Income  Tax  New_Income
0    1      John Doe  29.0  United State      M  55000.0  10%     60500.0
1    1      John Doe  29.0  United State      M  55000.0  10%     60500.0
2    2    Jane Smith  50.0        Canada      F  62000.0  20%     68200.0
3    3          Alex  50.0  United State      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0         Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0         China      M  51000.0  10%     56100.0
6    6           NaN  45.0         India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0           NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0  United State      F  62000.0  20%     68200.0
9    9   Carlos Ruiz  50.0        Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0  United State    NaN  58000.0  10%     63800.0

# Ranking

In [20]:
sorted_df['Ranking'] = sorted_df['Income'].rank()
sorted_df

,Id,Name,Age,Country,Gender,Income,Tax,New_Income,Ranking
9,9,Carlos Ruiz,50.0,Mexico,M,45000.0,10%,49500.0,1.0
3,3,Alex,50.0,United State,U,47000.0,10%,51700.0,2.0
5,5,Li Wei,27.0,China,M,51000.0,10%,56100.0,3.0
0,1,John Doe,29.0,United State,M,55000.0,10%,60500.0,4.5
1,1,John Doe,29.0,United State,M,55000.0,10%,60500.0,4.5
10,10,Emily Davis,31.0,United State,NaN,58000.0,10%,63800.0,6.0
8,8,Rachel Lee,29.0,United State,F,62000.0,20%,68200.0,7.5
2,2,Jane Smith,50.0,Canada,F,62000.0,20%,68200.0,7.5
7,7,Ahmed Khan,38.0,NaN,M,68000.0,20%,74800.0,9.0
6,6,NaN,45.0,India,F,73000.0,20%,80300.0,10.0
4,4,Maria Garcia,34.0,Spain,F,NaN,10%,NaN,NaN