In [1]:
import pandas as pd

In [11]:
df = pd.DataFrame({
    "country":['USA','USA','India','India'],
    "year":[2020,2021,2020,2021],
    "sales": [100,120,90,110],
    'profit': [20,25,18,22],
    'tax':[10,20,30,40]
})

In [12]:
df

  country  year  sales  profit  tax
0     USA  2020    100      20   10
1     USA  2021    120      25   20
2   India  2020     90      18   30
3   India  2021    110      22   40

In [13]:

# using this we can reduce the columns 

melted_df = df.melt(
    id_vars = ["country","year"],
    value_vars = ["sales","profit","tax"],
    var_name = "metrics",
    value_name= "value"   
)

melted_df

   country  year metrics  value
0      USA  2020   sales    100
1      USA  2021   sales    120
2    India  2020   sales     90
3    India  2021   sales    110
4      USA  2020  profit     20
5      USA  2021  profit     25
6    India  2020  profit     18
7    India  2021  profit     22
8      USA  2020     tax     10
9      USA  2021     tax     20
10   India  2020     tax     30
11   India  2021     tax     40

In [ ]:
# threw pivot we can increse the columns