In [1]:
import pandas as pd

In [2]:
df_customer = pd.DataFrame({
    "customer_id":[1,2,3,4],
    "name" :['Adam','Bob',"Chalrie",'Dave']
})

df_order = pd.DataFrame({
    "order_id": [ 101,102,103,104],
    "customer_id": [2,1,4,5],
    "amount":[250,120,300,100]
})

In [3]:
df_customer

   customer_id     name
0            1     Adam
1            2      Bob
2            3  Chalrie
3            4     Dave

In [4]:
df_order

   order_id  customer_id  amount
0       101            2     250
1       102            1     120
2       103            4     300
3       104            5     100

In [6]:
pd.merge(df_customer,df_order, on = "customer_id")  # inner join  


#  "on" selects the common data

   customer_id  name  order_id  amount
0            1  Adam       102     120
1            2   Bob       101     250
2            4  Dave       103     300

In [7]:
pd.merge(df_customer,df_order, on = "customer_id" , how = "left")  # Left join

   customer_id     name  order_id  amount
0            1     Adam     102.0   120.0
1            2      Bob     101.0   250.0
2            3  Chalrie       NaN     NaN
3            4     Dave     103.0   300.0

In [8]:
pd.merge(df_customer,df_order, on = "customer_id" , how = "right")  # right join

   customer_id  name  order_id  amount
0            2   Bob       101     250
1            1  Adam       102     120
2            4  Dave       103     300
3            5   NaN       104     100

In [9]:
pd.merge(df_customer,df_order, on = "customer_id" , how = "outer")  # outer join 


# outer mege all the data and fill nan if there was any missing value

   customer_id     name  order_id  amount
0            1     Adam     102.0   120.0
1            2      Bob     101.0   250.0
2            3  Chalrie       NaN     NaN
3            4     Dave     103.0   300.0
4            5      NaN     104.0   100.0